Importando bibliotecas

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Carregando Dados

In [33]:
imunizacao = pd.read_csv(
    "ImunizaçãoPorMunicípio2022.csv",
    sep=";",
    encoding="latin1"
)

obitos = pd.read_csv(
    "ÓbitosPorMunicípio2022.csv",
    sep=";",
    encoding="latin1",
    skiprows=3
)

nascidos = pd.read_csv(
    "NascidosVivosPorMunicípio2022.csv",
    sep=";",
    encoding="latin1",
    skiprows=3
)

Verificando o que foi carregado

In [34]:
print("Imunização:", imunizacao.shape)
print("Óbitos:", obitos.shape)
print("Nascidos vivos:", nascidos.shape)

Imunização: (5570, 2)
Óbitos: (4078, 2)
Nascidos vivos: (5604, 2)

Colunas

In [35]:
print("COLUNAS - IMUNIZAÇÃO")
print(imunizacao.columns.tolist())

print("\nCOLUNAS - ÓBITOS")
print(obitos.columns.tolist())

print("\nCOLUNAS - NASCIDOS VIVOS")
print(nascidos.columns.tolist())

imunizacao.columns = ["Municipio", "Poliomielite"]
obitos.columns = ["Municipio", "Obitos"]
nascidos.columns = ["Municipio", "Nascidos_Vivos"]

print("COLUNAS - IMUNIZAÇÃO")
print(imunizacao.columns.tolist())

print("\nCOLUNAS - ÓBITOS")
print(obitos.columns.tolist())

print("\nCOLUNAS - NASCIDOS VIVOS")
print(nascidos.columns.tolist())

COLUNAS - IMUNIZAÇÃO
['Municï¿½pio', 'Poliomielite']

COLUNAS - ÓBITOS
['Municï¿½pio', 'ï¿½bitos_p/Residï¿½nc']

COLUNAS - NASCIDOS VIVOS
['Municï¿½pio', 'Nascim_p/resid.mï¿½e']
COLUNAS - IMUNIZAÇÃO
['Municipio', 'Poliomielite']

COLUNAS - ÓBITOS
['Municipio', 'Obitos']

COLUNAS - NASCIDOS VIVOS
['Municipio', 'Nascidos_Vivos']

Primeiros valores

In [36]:
display(imunizacao.head())
display(obitos.head())
display(nascidos.head())

                       Municipio Poliomielite
0  110001 ALTA FLORESTA D\'OESTE       101,50
1               110002 ARIQUEMES        85,40
2                  110003 CABIXI        97,10
3                  110004 CACOAL        85,66
4              110005 CEREJEIRAS        95,17

                      Municipio  Obitos
0  110001 ALTA FLORESTA D'OESTE     2.0
1              110002 ARIQUEMES    32.0
2                 110004 CACOAL    13.0
3             110005 CEREJEIRAS     1.0
4      110006 COLORADO DO OESTE     4.0

                      Municipio Nascidos_Vivos
0       MUNICIPIO IGNORADO - RO              2
1  110001 ALTA FLORESTA D'OESTE            368
2              110002 ARIQUEMES           1505
3                 110003 CABIXI             64
4                 110004 CACOAL           1353

In [37]:
imunizacao.info()
obitos.info()
nascidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Municipio     5570 non-null   str
 1   Poliomielite  5570 non-null   str
dtypes: str(2)
memory usage: 87.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 4078 entries, 0 to 4077
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Municipio  4078 non-null   str
 1   Obitos     4073 non-null   float64
dtypes: float64(1), str(1)
memory usage: 63.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 5604 entries, 0 to 5603
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Municipio       5604 non-null   str
 1   Nascidos_Vivos  5599 non-null   str
dtypes: str(2)
memory usage: 87.7 KB

In [38]:
print("ÓBITOS COM VALORES AUSENTES:")
display(obitos[obitos["Obitos"].isna()])

print("\nNASCIDOS VIVOS COM VALORES AUSENTES:")
display(nascidos[nascidos["Nascidos_Vivos"].isna()])

ÓBITOS COM VALORES AUSENTES:

                                              Municipio  Obitos
4073   Fonte: MS/SVSA/CGIAE - Sistema de Informaï¿½ï...     NaN
4074                                             Notas:     NaN
4075   Dados finais disponï¿½veis atï¿½ 2024 - data ...     NaN
4076   Dados de 2025 - Preliminares - data de extraï...     NaN
4077   Dados de 2026 - 1a prï¿½via - data de extraï¿...     NaN

NASCIDOS VIVOS COM VALORES AUSENTES:

                                              Municipio Nascidos_Vivos
5599   Fonte: MS/SVSA/CGIAE - Sistema de Informaï¿½ï...            NaN
5600                                             Notas:            NaN
5601   Dados finais disponï¿½veis atï¿½ 2024 - data ...            NaN
5602   Dados de 2025 - Preliminares - data de extraï...            NaN
5603   Dados de 2026 - 1a prï¿½via - data de extraï¿...            NaN

In [39]:
print("ÓBITOS - ÚLTIMAS LINHAS")
display(obitos.tail(10))

print("\nNASCIDOS VIVOS - ÚLTIMAS LINHAS")
display(nascidos.tail(10))

print("\nIMUNIZAÇÃO - ÚLTIMAS LINHAS")
display(imunizacao.tail(10))

ÓBITOS - ÚLTIMAS LINHAS

                                              Municipio   Obitos
4068                                  522200 VIANOPOLIS      4.0
4069                              522205 VICENTINOPOLIS      4.0
4070                                    522220 VILA BOA      1.0
4071                                    530010 BRASILIA    362.0
4072                                              Total  32257.0
4073   Fonte: MS/SVSA/CGIAE - Sistema de Informaï¿½ï...      NaN
4074                                             Notas:      NaN
4075   Dados finais disponï¿½veis atï¿½ 2024 - data ...      NaN
4076   Dados de 2025 - Preliminares - data de extraï...      NaN
4077   Dados de 2026 - 1a prï¿½via - data de extraï¿...      NaN

NASCIDOS VIVOS - ÚLTIMAS LINHAS

                                              Municipio Nascidos_Vivos
5594                                    522220 VILA BOA             40
5595                               522230 VILA PROPICIO             73
5596                                    530010 BRASILIA          35928
5597                        000000 Ignorado ou exterior              -
5598                                              Total        2561922
5599   Fonte: MS/SVSA/CGIAE - Sistema de Informaï¿½ï...            NaN
5600                                             Notas:            NaN
5601   Dados finais disponï¿½veis atï¿½ 2024 - data ...            NaN
5602   Dados de 2025 - Preliminares - data de extraï...            NaN
5603   Dados de 2026 - 1a prï¿½via - data de extraï¿...            NaN

IMUNIZAÇÃO - ÚLTIMAS LINHAS

                       Municipio Poliomielite
5560               522170 URUANA        87,41
5561               522180 URUTAI        95,83
5562  522185 VALPARAISO DE GOIAS        89,83
5563               522190 VARJAO       124,14
5564           522200 VIANOPOLIS       111,05
5565       522205 VICENTINOPOLIS        70,50
5566             522220 VILA BOA       137,25
5567        522230 VILA PROPICIO        94,34
5568             530010 BRASILIA        78,33
5569                       Total        77,20

In [40]:
print(imunizacao["Poliomielite"].head(20).to_list())

['101,50', '85,40', '97,10', '85,66', '95,17', '101,97', '101,87', '93,68', '89,17', '52,91', '84,87', '79,28', '83,96', '106,09', '78,83', '95,85', '72,47', '74,52', '102,08', '84,83']

Limpeza de "Imunização" e convertendo cobertura para numerico

In [41]:
imunizacao = imunizacao[
    imunizacao["Municipio"].str.match(r"^\d{6}\s", na=False)
].copy()

imunizacao["Poliomielite"] = (
    imunizacao["Poliomielite"]
    .str.replace(",", ".", regex=False)
    .astype(float)
)

Limpando óbitos

In [42]:
obitos = obitos[
    obitos["Municipio"].str.match(r"^\d{6}\s", na=False)
].copy()

obitos = obitos[
    obitos["Municipio"].str.match(r"^\d{6}\s", na=False)
].copy()

Limpando nascidos vivos

In [43]:
nascidos = nascidos[
    nascidos["Municipio"].str.match(r"^\d{6}\s", na=False)
].copy()

nascidos = nascidos[
    nascidos["Municipio"].str.match(r"^\d{6}\s", na=False)
].copy()

Criando código para os municípios (nova coluna)

In [44]:
imunizacao["codigo_municipio"] = imunizacao["Municipio"].str.extract(r"^(\d{6})")[0]

obitos["codigo_municipio"] = obitos["Municipio"].str.extract(r"^(\d{6})")[0]

nascidos["codigo_municipio"] = nascidos["Municipio"].str.extract(r"^(\d{6})")[0]

Cruzando dados

In [45]:
df = pd.merge(
    imunizacao[["codigo_municipio", "Municipio", "Poliomielite"]],
    obitos[["codigo_municipio", "Obitos"]],
    on="codigo_municipio",
    how="inner"
)

In [46]:
df = pd.merge(
    df,
    nascidos[["codigo_municipio", "Nascidos_Vivos"]],
    on="codigo_municipio",
    how="inner"
)

In [47]:
df = df.rename(columns={
    "Poliomielite": "Cobertura_Poliomielite",
    "Óbitos_p/Residênc": "Obitos",
    "Nascim_p/resid.mãe": "Nascidos_Vivos"
})

Criando a taxa de mortalidade

In [48]:
nascidos = nascidos[
    nascidos["codigo_municipio"] != "000000"
].copy()

In [49]:
nascidos["Nascim_p/resid.mãe"] = pd.to_numeric(
    nascidos["Nascidos_Vivos"],
    errors="coerce"
)

In [50]:
df["Nascidos_Vivos"] = pd.to_numeric(
    df["Nascidos_Vivos"],
    errors="coerce"
)

In [51]:
df["Taxa_Mortalidade"] = (
    df["Obitos"] /
    df["Nascidos_Vivos"]
) * 1000

Criando as regiões

In [52]:
uf_por_codigo = {
    "11": "RO",
    "12": "AC",
    "13": "AM",
    "14": "RR",
    "15": "PA",
    "16": "AP",
    "17": "TO",
    "21": "MA",
    "22": "PI",
    "23": "CE",
    "24": "RN",
    "25": "PB",
    "26": "PE",
    "27": "AL",
    "28": "SE",
    "29": "BA",
    "31": "MG",
    "32": "ES",
    "33": "RJ",
    "35": "SP",
    "41": "PR",
    "42": "SC",
    "43": "RS",
    "50": "MS",
    "51": "MT",
    "52": "GO",
    "53": "DF"
}

In [53]:
df["UF"] = df["codigo_municipio"].str[:2].map(uf_por_codigo)

In [54]:
regiao_por_uf = {
    "RO": "Norte",
    "AC": "Norte",
    "AM": "Norte",
    "RR": "Norte",
    "PA": "Norte",
    "AP": "Norte",
    "TO": "Norte",
    
    "MA": "Nordeste",
    "PI": "Nordeste",
    "CE": "Nordeste",
    "RN": "Nordeste",
    "PB": "Nordeste",
    "PE": "Nordeste",
    "AL": "Nordeste",
    "SE": "Nordeste",
    "BA": "Nordeste",
    
    "MG": "Sudeste",
    "ES": "Sudeste",
    "RJ": "Sudeste",
    "SP": "Sudeste",
    
    "PR": "Sul",
    "SC": "Sul",
    "RS": "Sul",
    
    "MS": "Centro-Oeste",
    "MT": "Centro-Oeste",
    "GO": "Centro-Oeste",
    "DF": "Centro-Oeste"
}

df["Região"] = df["UF"].map(regiao_por_uf)

Tabela Final

In [55]:
df = df.rename(columns={
    "Poliomielite": "Cobertura_Poliomielite",
    "Óbitos_p/Residênc": "Obitos",
    "Nascim_p/resid.mãe": "Nascidos_Vivos"
})

In [56]:
df = df[
    [
        "codigo_municipio",
        "Municipio",
        "UF",
        "Região",
        "Cobertura_Poliomielite",
        "Obitos",
        "Nascidos_Vivos",
        "Taxa_Mortalidade"
    ]
]

Verificações :

In [57]:
print(df.shape)
print(df.dtypes)
print(df.isna().sum())
display(df.describe())

(4062, 8)
codigo_municipio              str
Municipio                     str
UF                            str
Região                        str
Cobertura_Poliomielite    float64
Obitos                    float64
Nascidos_Vivos              int64
Taxa_Mortalidade          float64
dtype: object
codigo_municipio          0
Municipio                 0
UF                        0
Região                    0
Cobertura_Poliomielite    0
Obitos                    0
Nascidos_Vivos            0
Taxa_Mortalidade          0
dtype: int64

       Cobertura_Poliomielite       Obitos  Nascidos_Vivos  Taxa_Mortalidade
count             4062.000000  4062.000000     4062.000000       4062.000000
mean                89.872546     7.936238      607.124077         17.713380
std                 22.029220    32.559133     2805.745772         12.782438
min                 12.090000     1.000000        7.000000          1.562500
25%                 76.905000     1.000000      100.000000          9.912674
50%                 88.530000     3.000000      204.000000         14.285714
75%                101.740000     6.000000      445.750000         21.276596
max                316.000000  1437.000000   132050.000000        166.666667

Quantos municípios possuem cobertura acima de 100% e quantos têm poucos nascidos vivos

In [58]:
print("Cobertura acima de 100%:")
print((df["Cobertura_Poliomielite"] > 100).sum())

print("\nCobertura igual ou abaixo de 100%:")
print((df["Cobertura_Poliomielite"] <= 100).sum())

Cobertura acima de 100%:
1114

Cobertura igual ou abaixo de 100%:
2948

In [59]:
print("Municípios com menos de 50 nascidos vivos:")
print((df["Nascidos_Vivos"] < 50).sum())

print("\nMunicípios com menos de 100 nascidos vivos:")
print((df["Nascidos_Vivos"] < 100).sum())

Municípios com menos de 50 nascidos vivos:
361

Municípios com menos de 100 nascidos vivos:
1004

In [60]:
print("Maiores coberturas:")
display(
    df.nlargest(10, "Cobertura_Poliomielite")[
        ["Municipio", "Cobertura_Poliomielite"]
    ]
)
print("\nMaiores taxas de mortalidade:")
display(
    df.nlargest(10, "Taxa_Mortalidade")[
        ["Municipio", "Nascidos_Vivos", "Obitos", "Taxa_Mortalidade"]
    ]
)

Maiores coberturas:

                           Municipio  Cobertura_Poliomielite
559       211195 SUCUPIRA DO RIACHAO                  316.00
2130         313830 LEANDRO FERREIRA                  235.00
1629                     291330 ICHU                  230.77
4003              521480 NOVA AURORA                  228.57
3650     431673 SANTA CECILIA DO SUL                  220.00
370                   172097 TALISMA                  208.70
534   211065 SAO DOMINGOS DO AZEITAO                  200.00
1126            251365 JOCA CLAUDINO                  192.86
3903          510885 NOVA MARILANDIA                  181.82
2256                 315300 PRATINHA                  175.76

Maiores taxas de mortalidade:

                      Municipio  Nascidos_Vivos  Obitos  Taxa_Mortalidade
3720              432255 VANINI              12     2.0        166.666667
3715      432235 UNIAO DA SERRA               7     1.0        142.857143
3322            420475 CUNHATAI              16     2.0        125.000000
4053            522157 UIRAPURU              35     4.0        114.285714
711    221037 SAO LUIS DO PIAUI              29     3.0        103.448276
2017       312460 ESTRELA DALVA              20     2.0        100.000000
3514          430511 CENTENARIO              20     2.0        100.000000
3703              432149 TOROPI              20     2.0        100.000000
3027    410315 BOM JESUS DO SUL              41     4.0         97.560976
590   220117 BARRA D\'ALCANTARA              42     4.0         95.238095

In [61]:
# 1. O valor real na coluna já está corrompido, ou só o print está errado?
col = nascidos.columns[1]  # ou o nome que já apareceu quebrado
print(repr(col))
print([hex(ord(c)) for c in col])

'Nascidos_Vivos'
['0x4e', '0x61', '0x73', '0x63', '0x69', '0x64', '0x6f', '0x73', '0x5f', '0x56', '0x69', '0x76', '0x6f', '0x73']